#!/usr/bin/env Rscript
# Create per-cell metadata for per-clone SPRINTER S-phase analysis.
#
# Inputs:
#   - MPNST_all_k_means_K22_clusters.rds  (K=22, combined 10X+DLP+)
#   - Per-cluster TSVs in MEDICC2_input/per_cluster_10X_DLP/minseg_2.5/
#
# Output: scDNA/2_clustering/metadata_cells.tsv
#
# Columns:
#   barcode         raw cell barcode as it appears in the CHISEL RDR CELL column
#   region          P | R1 | R2 | R3 | R4 | R5
#   technology      10X | DLP
#   kmeans_cluster  1-22
#   clone_label     healthy | removed | P_1 | R1_1 | ...
#   cell_type       healthy | removed | tumour
#   chisel_rdr_path absolute path to the CHISEL rdr.tsv for this cell
#
# NOTE: 10X CHISEL RDR files are generated by scDNA/4_sprinter/chisel/chisel_rdr_10x.sh.
# Run that script first if you want 10X-only or combined SPRINTER modes.
# The DLP+ CHISEL RDR files already exist.

# ── Paths ─────────────────────────────────────────────────────────────────────

RDS_PATH    <- "/mnt/iribhm/people/mtarabichi/MPNST/pvanloo_20250618/Haixi/10X_DLP/results/ASCAT.sc/MPNST_all_k_means_K22_clusters.rds"
CLUSTER_DIR <- "/srv/home/aste0033/projects/MPNST/Haixi/scDNA/MEDICC2_input/per_cluster_10X_DLP/minseg_2.5"
OUT_FILE    <- "scDNA/2_clustering/metadata_cells.tsv"

# ── CHISEL RDR paths: DLP+ (exist) and 10X (generated by chisel_rdr_10x.sh) ──

# 10X sample-to-region mapping: FIT208A3=R1, A4=R2, A5=R3, A6=R4, A7=R5, A8=P
DLP_RDR <- c(
  P  = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/P/rdr.tsv",
  R1 = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/R1/rdr.tsv",
  R2 = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/R2/rdr.tsv",
  R3 = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/R3/rdr.tsv",
  R4 = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/R4/rdr.tsv",
  R5 = "/srv/home/aste0033/projects/MPNST/scDNA/CHISEL/DLPp/R5/rdr.tsv"
)

TEN_X_RDR <- c(
  P  = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A8/rdr.tsv",
  R1 = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A3/rdr.tsv",
  R2 = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A4/rdr.tsv",
  R3 = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A5/rdr.tsv",
  R4 = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A6/rdr.tsv",
  R5 = "/mnt/iribhm/homes/aste0033/projects/MPNST/scDNA/CHISEL/10X/FIT208A7/rdr.tsv"
)

# ── Load K-means cluster assignments ──────────────────────────────────────────

cat("Loading K-means cluster RDS (K=22)...\n")
clusters <- readRDS(RDS_PATH)
cat("Number of clusters:", length(clusters), "\n")
cat("First 5 barcodes in cluster 1:\n")
print(head(clusters[[1]], 5))

meta <- do.call(rbind, lapply(seq_along(clusters), function(k) {
  data.frame(barcode_raw = clusters[[k]], kmeans_cluster = k,
             stringsAsFactors = FALSE)
}))

# ── Parse region, technology, CHISEL barcode from barcode_raw ─────────────────

# Barcode format in RDS:
#   10X: "R1_10X_CTGAAGTCATTATCCT-1"
#   DLP: "P_DLP_LES4677A4_124668_16x_18y.bam"  (ends in .bam)
#
# CHISEL RDR CELL column uses the raw barcode without region/tech prefix and
# without the .bam suffix.

meta$region     <- sub("_.*", "", meta$barcode_raw)
meta$technology <- sub("^[^_]+_([^_]+)_.*", "\\1", meta$barcode_raw)
meta$barcode    <- sub("^[^_]+_[^_]+_", "", meta$barcode_raw)   # strip region_tech prefix
meta$barcode    <- sub("\\.bam$", "", meta$barcode)              # strip .bam (DLP only)
meta$barcode    <- ifelse(meta$technology == "10X",
                          sub("-[0-9]+$", "", meta$barcode),     # strip GEM group suffix (-1 etc.)
                          meta$barcode)

# ── Assign cell_type ──────────────────────────────────────────────────────────

meta$cell_type <- ifelse(meta$kmeans_cluster == 1, "healthy",
                  ifelse(meta$kmeans_cluster == 2, "removed", "tumour"))

# ── Assign clone_label from per-cluster TSVs ──────────────────────────────────

meta$clone_label <- meta$cell_type   # default: healthy/removed/tumour

tsv_files <- list.files(CLUSTER_DIR, pattern = "\\.tsv$", full.names = TRUE)
cat("\nPer-cluster TSVs found:", length(tsv_files), "\n")

# Clone label extracted from filename suffix:
# "scDNA_22_kmeans_10X_DLP_2.5_R1_1.tsv" -> "R1_1"
# Captures the last two underscore-delimited tokens before .tsv
clone_from_file <- sub("^.*_([^_]+_[0-9]+)\\.tsv$", "\\1", basename(tsv_files))
cat("Clone labels:", paste(clone_from_file, collapse = ", "), "\n")

# Read unique sample_ids from each TSV and map to clone label
# sample_id format matches barcode_raw exactly (same pipeline output)
tsv_data <- do.call(rbind, lapply(seq_along(tsv_files), function(i) {
  df <- read.table(tsv_files[i], header = TRUE, sep = "\t",
                   colClasses = c(sample_id = "character",
                                  chrom = "NULL", start = "NULL",
                                  end = "NULL", cn_a = "NULL", cn_b = "NULL"))
  data.frame(barcode_raw = unique(df$sample_id),
             clone_label = clone_from_file[i],
             stringsAsFactors = FALSE)
}))

# Join: update clone_label for tumour cells
idx <- match(meta$barcode_raw, tsv_data$barcode_raw)
meta$clone_label[meta$cell_type == "tumour"] <- tsv_data$clone_label[
  idx[meta$cell_type == "tumour"]
]

# Warn about unmatched tumour cells (in cluster 2 or size-filtered clusters)
unmatched <- sum(meta$cell_type == "tumour" & is.na(meta$clone_label))
if (unmatched > 0) {
  cat("\nWARNING:", unmatched,
      "tumour cells have no clone_label (likely in removed/size-filtered cluster)\n")
  meta$clone_label[meta$cell_type == "tumour" & is.na(meta$clone_label)] <- "unassigned"
}

# ── Assign chisel_rdr_path ────────────────────────────────────────────────────

rdr_lookup <- rbind(
  data.frame(region = names(DLP_RDR),    technology = "DLP",
             chisel_rdr_path = unname(DLP_RDR),    stringsAsFactors = FALSE),
  data.frame(region = names(TEN_X_RDR),  technology = "10X",
             chisel_rdr_path = unname(TEN_X_RDR),  stringsAsFactors = FALSE)
)

meta <- merge(meta, rdr_lookup, by = c("region", "technology"), all.x = TRUE)

# ── Sanity checks ─────────────────────────────────────────────────────────────

cat("\n=== Sanity checks ===\n")
cat("Total cells:", nrow(meta), "\n")

cat("\nBreakdown by technology and cell_type:\n")
print(table(meta$technology, meta$cell_type))

cat("\nBreakdown by clone_label:\n")
tbl <- as.data.frame(table(clone_label = meta$clone_label,
                            cell_type   = meta$cell_type))
tbl <- tbl[tbl$Freq > 0, ]
print(tbl[order(tbl$cell_type, tbl$clone_label), ], row.names = FALSE)

n_na_path <- sum(is.na(meta$chisel_rdr_path))
cat("\nCells with NA chisel_rdr_path:", n_na_path, "\n")
if (n_na_path > 0) {
  cat("Breakdown:\n")
  print(table(meta$region[is.na(meta$chisel_rdr_path)],
              meta$technology[is.na(meta$chisel_rdr_path)]))
}

n_missing_10x <- sum(meta$technology == "10X" & !file.exists(meta$chisel_rdr_path),
                     na.rm = TRUE)
if (n_missing_10x > 0) {
  cat("\nWARNING:", n_missing_10x,
      "10X cells point to missing CHISEL RDR files.\n")
  cat("Run scDNA/4_sprinter/chisel/chisel_rdr_10x.sh to generate them.\n")
  cat("Until then, 10X-only and combined SPRINTER modes will be skipped for those cells.\n")
}

# ── Write output ──────────────────────────────────────────────────────────────

meta <- meta[, c("barcode", "region", "technology", "kmeans_cluster",
                 "clone_label", "cell_type", "chisel_rdr_path")]
meta <- meta[order(meta$cell_type, meta$clone_label, meta$technology, meta$barcode), ]

write.table(meta, OUT_FILE, sep = "\t", quote = FALSE, row.names = FALSE)
cat("\nMetadata written to:", OUT_FILE, "\n")
cat("Rows:", nrow(meta), "\n")
